name: Cypress Regression Tests
#nome do workflow

on: [push]
#quando o workflow vai ser executado. Sempre que eu fizer um push no repositório.

jobs:

  ui-chrome-tests:
  #único job deste workflow
    runs-on: ubuntu-latest
    #o sistema operacional que vai rodar esse workflow
    container: cypress/browsers:node14.17.0-chrome88-ff89
    #template/container onde será montada a máquiva virtual ubunto para rodar os testes no chrome
    strategy:
      fail-fast: false
      #o valor false é usado para que o cypress não aborte o processo de teste
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install
          wait-on: ${{ secrets.BASE_URL }}
          wait-on-timeout: 120
          browser: chrome
          record: true
          group: 'UI - Chrome'
          spec: cypress/integration/*
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
